apiVersion: v1
kind: Pod

metadata:
  name: stress-memory
spec:
  containers:
  - name: stress-memory
    imagePullPolicy: IfNotPresent
    image: yaopolytech/stress
    command: ["sh", "-c", "stress -m 1 --vm-bytes 512m"]
    resources:
      limits:
        cpu: "1"
        memory: 1024Mi
      requests:
        cpu: "1"
        memory: 256Mi
